# Generated by Django 5.2.7 on 2025-11-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='auto',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
