# Generated by Django 5.2.7 on 2025-11-04 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_auto_fecha_publicacion_auto_anio_auto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
